---
- hosts: all
  become: true
  tasks:
    - name: Update the package list and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install apache httpd (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'

