- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    key_name: "{{key_pair}}"
    vpc_subnet_id: subnet-04bd2630627910275
    instance_type: "{{instance_type}}"
    security_group: default
    region: ap-south-1
    aws_access_key: "{{ aws_access_key }}"  # From vault as defined
    aws_secret_key: "{{ aws_secret_key }}"  # From vault as defined      
    network:
      assign_public_ip: true
    image_id: "{{ami_id}}"
    tags:
      Environment: Testing

